#ifndef CONSTANTS_H
#define CONSTANTS_H

#define OFFSET_MAGIC 0x00
#define OFFSET_PAGE_SIZE 0x10
#define OFFSET_FILE_FORMAT_WRITE_VERSION 0x12
#define OFFSET_FILE_FORMAT_READ 0x13
#define OFFSET_RESERVED_SPACE 0x14
#define OFFSET_MAX_EMBED_PAYLOAD_FRAC 0x15
#define OFFSET_MIN_EMBED_PAYLOAD_FRAC 0x16
#define OFFSET_LEAF_PAYLOAD_FRAC 0x17
#define OFFSET_FILE_CHANGE_COUNTER 0x18
#define OFFSET_HEADER_DB_SIZE 0x1C
#define OFFSET_FIRST_FREELIST_TRUNK 0x20
#define OFFSET_TOTAL_FREELIST_PAGES 0x24
#define OFFSET_SCHEMA_COOKIE 0x28
#define OFFSET_SCHEMA_FORMAT_NUMBER 0x2C
#define OFFSET_DEFAULT_PAGE_CACHE_SIZE 0x30
#define OFFSET_PAGE_NUMBER_LARGEST_ROOT 0x34
#define OFFSET_DB_TEXT_ENCODING 0x38
#define OFFSET_USER_VERSION 0x3C
#define OFFSET_INCREMENTAL_VACCUM_MODE 0x40
#define OFFSET_APPLICATION_ID 0x44
#define OFFSET_RESERVED_EXPANSION 0x48
#define OFFSET_VERSION_VALID_FOR 0x5C
#define OFFSET_SQLITE_VERSION_NUMBER 0x60

#define SQLITE_MAGIC "SQLite format 3\0"

#endif
