#ifndef CONSTANTS_H
#define CONSTANTS_H

#define OFFSET_MAGIC 0x00
#define OFFSET_PAGE_SIZE 0x10
#define OFFSET_FILE_FORMAT_WRITE_VERSION 0x12
#define OFFSET_FILE_FORMAT_READ 0x13
#define OFFSET_RESERVED_SPACE 0x14
#define OFFSET_MAX_EMBED_PAYLOAD_FRAC 0x15
#define OFFSET_MIN_EMBED_PAYLOAD_FRAC 0x16
#define OFFSET_LEAF_PAYLOAD_FRAC 0x17
#define OFFSET_FILE_CHANGE_COUNTER 0x18
#define OFFSET_HEADER_DB_SIZE 0x1C
#define OFFSET_FIRST_FREELIST_TRUNK 0x20
#define OFFSET_TOTAL_FREELIST_PAGES 0x24
#define OFFSET_SCHEMA_COOKIE 0x28
#define OFFSET_SCHEMA_FORMAT_NUMBER 0x2C
#define OFFSET_DEFAULT_PAGE_CACHE_SIZE 0x30
#define OFFSET_PAGE_NUMBER_LARGEST_ROOT 0x34
#define OFFSET_DB_TEXT_ENCODING 0x38
#define OFFSET_USER_VERSION 0x3C
#define OFFSET_INCREMENTAL_VACCUM_MODE 0x40
#define OFFSET_APPLICATION_ID 0x44
#define OFFSET_RESERVED_EXPANSION 0x48
#define OFFSET_VERSION_VALID_FOR 0x5C
#define OFFSET_SQLITE_VERSION_NUMBER 0x60

#define SQLITE_MAGIC "SQLite format 3\0"

// b-tree header offsets
#define OFFSET_BTREE_PAGE_TYPE 0x00
#define OFFSET_BTREE_FIRST_FREEBLOCK 0x01 
#define OFFSET_BTREE_CELL_COUNT 0x03
#define OFFSET_BTREE_CELL_CONTENT_START 0x05
#define OFFSET_BTREE_FRAG_FREE_BYTES 0x07
#define OFFSET_BTREE_RIGHTMOST_POINTER 0x08

// Page types
#define PAGE_TYPE_INTERIOR_INDEX 0x02
#define PAGE_TYPE_INTERIOR_TABLE 0x05
#define PAGE_TYPE_LEAF_INDEX 0x0A
#define PAGE_TYPE_LEAF_TABLE 0x0D

// Serial Type Codes
#define SERIAL_TYPE_NULL 0
#define SERIAL_TYPE_INT8 1
#define SERIAL_TYPE_INT16 2
#define SERIAL_TYPE_INT24 3
#define SERIAL_TYPE_INT32 4
#define SERIAL_TYPE_INT48 5
#define SERIAL_TYPE_INT64 6
#define SERIAL_TYPE_FLOAT64 7
#define SERIAL_TYPE_ZERO 8
#define SERIAL_TYPE_ONE 9
#define SERIAL_TYPE_INTERNAL1 10
#define SERIAL_TYPE_INTERNAL2 11
// N >= 12 and even: BLOB of length (N-12)/2
// N >= 13 and odd: TEXT of length (N-13)/2

// Content sizes for serial types
#define SERIAL_SIZE_NULL 0
#define SERIAL_SIZE_INT8 1
#define SERIAL_SIZE_INT16 2
#define SERIAL_SIZE_INT24 3
#define SERIAL_SIZE_INT32 4
#define SERIAL_SIZE_INT48 6
#define SERIAL_SIZE_INT64 8
#define SERIAL_SIZE_FLOAT64 8
#define SERIAL_SIZE_ZERO 0
#define SERIAL_SIZE_ONE 0

#endif
